export const mockSellerData = {
  shopData: {
    id: 1,
    shopName: 'Fresh Mart',
    ownerName: 'John Doe',
    mobile: '9876543210',
    email: 'freshmart@example.com',
    address: '123 Market Street, Mumbai',
    description: 'Your local source for fresh groceries and daily essentials',
    verified: true,
    rating: 4.5,
    totalReviews: 128,
    joinedDate: '2023-01-15',
  },

  products: [
    {
      id: 1,
      name: 'Organic Tomatoes',
      category: 'Vegetables',
      price: 60,
      originalPrice: 70,
      stock: 25,
      image: '🍅',
      status: 'active',
      views: 145,
      likes: 23,
      unit: 'kg',
      description: 'Fresh, locally sourced organic tomatoes',
    },
    {
      id: 2,
      name: 'Basmati Rice 5kg',
      category: 'Grains',
      price: 450,
      originalPrice: 500,
      stock: 5,
      image: '🌾',
      status: 'active',
      views: 89,
      likes: 12,
      unit: 'pack',
      description: 'Premium quality aged basmati rice',
    },
    {
      id: 3,
      name: 'Fresh Milk 1L',
      category: 'Dairy',
      price: 65,
      originalPrice: 65,
      stock: 0,
      image: '🥛',
      status: 'out_of_stock',
      views: 67,
      likes: 8,
      unit: 'L',
      description: 'Farm fresh milk, delivered daily',
    },
  ],

  posts: [
    {
      id: 1,
      type: 'offer',
      content: 'Weekend special! 20% off on all fresh vegetables 🥬',
      images: [],
      timestamp: '2024-01-20T10:30:00Z',
      likes: 45,
      comments: 12,
      shares: 5,
    },
    {
      id: 2,
      type: 'new_arrival',
      content: 'Just arrived: Premium Kashmiri Apples 🍎',
      images: [],
      timestamp: '2024-01-19T15:45:00Z',
      likes: 32,
      comments: 8,
      shares: 3,
    },
  ],

  analytics: {
    today: {
      sales: 4500,
      orders: 12,
      visitors: 45,
      newCustomers: 3,
    },
    thisMonth: {
      sales: 125000,
      orders: 350,
      visitors: 1200,
      growth: 15,
    },
    topProducts: [
      { id: 1, name: 'Organic Tomatoes', sales: 45 },
      { id: 2, name: 'Basmati Rice 5kg', sales: 38 },
      { id: 3, name: 'Fresh Milk 1L', sales: 32 },
    ],
  },

  chats: [
    {
      id: 1,
      customer: {
        name: 'Priya Sharma',
        avatar: '👩‍💼',
        phone: '+91 98765 43210',
      },
      lastMessage: {
        text: 'Is the organic milk available?',
        timestamp: '2024-01-20T16:30:00Z',
        isFromCustomer: true,
        isRead: false,
      },
      unreadCount: 2,
      status: 'active',
    },
    {
      id: 2,
      customer: {
        name: 'Rajesh Kumar',
        avatar: '👨‍💻',
        phone: '+91 87654 32109',
      },
      lastMessage: {
        text: 'Thank you for the quick delivery!',
        timestamp: '2024-01-20T15:45:00Z',
        isFromCustomer: true,
        isRead: true,
      },
      unreadCount: 0,
      status: 'satisfied',
    },
  ],

  notifications: [
    {
      id: 1,
      type: 'order',
      title: 'New Order Received',
      message: 'Order #123 received from Priya Sharma',
      timestamp: '2024-01-20T16:30:00Z',
      isRead: false,
    },
    {
      id: 2,
      type: 'stock',
      title: 'Low Stock Alert',
      message: 'Basmati Rice 5kg is running low on stock',
      timestamp: '2024-01-20T14:20:00Z',
      isRead: true,
    },
  ],
};
